# Generated by Django 6.0.2 on 2026-06-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('AI', 'AI'), ('Java', 'Java')], default='Python', max_length=20),
        ),
    ]
