# Generated by Django 6.0.2 on 2026-06-19 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('AI', 'AI'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('C++', 'C++'), ('C#', 'C#'), ('PHP', 'PHP'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust'), ('TypeScript', 'TypeScript'), ('SQL', 'SQL'), ('HTML/CSS', 'HTML/CSS'), ('Other', 'Other')], default='Python', max_length=20),
        ),
    ]
