# Generated by Django 6.0.2 on 2026-09-24 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('tech_stack', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('development', 'In Development'), ('completed', 'Completed'), ('live', 'Live')], default='idea', max_length=20)),
                ('problem', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('looking_for_collaborators', models.BooleanField(default=False)),
                ('collaborator_types', models.CharField(blank=True, max_length=500)),
                ('original_description', models.TextField(blank=True)),
                ('ai_improved_description', models.TextField(blank=True)),
                ('ai_improved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
