# Generated by Django 6.0.2 on 2026-09-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_conversation_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='blog.project'),
        ),
    ]
