# Generated by Django 6.0.2 on 2026-09-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_conversation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
