# Generated by Django 6.1.1 on 2026-09-26 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_backfill_legacy_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('category', models.CharField(default='python', max_length=40)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('function_name', models.CharField(max_length=100)),
                ('starter_code', models.JSONField(default=dict)),
                ('example', models.JSONField(blank=True, default=dict)),
                ('constraints', models.JSONField(blank=True, default=list)),
                ('public_tests', models.JSONField(default=list)),
                ('hidden_tests', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('source_code', models.TextField()),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong answer'), ('COMPILATION_ERROR', 'Compilation error'), ('RUNTIME_ERROR', 'Runtime error'), ('TIME_LIMIT_EXCEEDED', 'Time limit exceeded'), ('INTERNAL_ERROR', 'Internal error')], max_length=30)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('execution_time', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_used', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='blog.practiceproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_ATTEMPTED', 'Not attempted'), ('ATTEMPTED', 'Attempted'), ('SOLVED', 'Solved')], default='NOT_ATTEMPTED', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('code_drafts', models.JSONField(blank=True, default=dict)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='blog.practiceproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_progress', to=settings.AUTH_USER_MODEL)),
                ('last_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_progress', to='blog.practicesubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'problem'), name='unique_practice_progress')],
            },
        ),
    ]
