# Generated by Django 6.1.1 on 2026-09-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_notification_followrequest'),
        ('blog', '0032_post_sequential_learning_enrollment_and_more'),
    ]

    operations = [
    ]
