# Generated by Django 6.1.1 on 2026-10-01 20:28

from django.conf import settings
from django.db import migrations, models


def deduplicate_personal_conversations(apps, schema_editor):
    Conversation = apps.get_model('blog', 'Conversation')
    Message = apps.get_model('blog', 'Message')
    seen = {}

    for conversation in Conversation.objects.filter(project__isnull=True).order_by('project_owner_id', 'participant_id', 'id'):
        key = tuple(sorted((conversation.project_owner_id, conversation.participant_id)))
        keep_id = seen.get(key)
        if keep_id is None:
            seen[key] = conversation.id
            continue

        Message.objects.filter(conversation_id=conversation.id).update(conversation_id=keep_id)
        conversation.delete()


def deduplicate_project_collaborators(apps, schema_editor):
    ProjectCollaborator = apps.get_model('blog', 'ProjectCollaborator')
    seen = set()

    for collaborator in ProjectCollaborator.objects.order_by('project_id', 'user_id', 'id'):
        key = (collaborator.project_id, collaborator.user_id)
        if key in seen:
            collaborator.delete()
        else:
            seen.add(key)


def deduplicate_project_views(apps, schema_editor):
    ProjectView = apps.get_model('blog', 'ProjectView')
    seen = set()

    for view in ProjectView.objects.filter(user__isnull=False).order_by('project_id', 'user_id', 'id'):
        key = (view.project_id, view.user_id)
        if key in seen:
            view.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_mocktest_alter_assignmentquestion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_personal_conversations, migrations.RunPython.noop),
        migrations.RunPython(deduplicate_project_collaborators, migrations.RunPython.noop),
        migrations.RunPython(deduplicate_project_views, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('project_owner', 'participant'), name='unique_personal_conversation'),
        ),
        migrations.AddConstraint(
            model_name='projectcollaborator',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_collaborator'),
        ),
        migrations.AddConstraint(
            model_name='projectview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('project', 'user'), name='unique_project_view_per_user'),
        ),
    ]
