# Generated by Django 6.0.2 on 2026-10-02 21:10

import re

from django.conf import settings
from django.db import migrations, models


def normalize_usernames_and_backfill_display_names(apps, schema_editor):
    database = schema_editor.connection.alias
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('blog', 'UserProfile')
    used_usernames = set()
    users = list(
        User.objects.using(database).order_by('pk')
    )
    temporary_usernames = set()

    for user in users:
        temporary_username = f'__vgh_migration_{user.pk}__'
        suffix = 2
        while (
            temporary_username in temporary_usernames
            or User.objects.using(database).filter(
                username=temporary_username
            ).exclude(pk=user.pk).exists()
        ):
            temporary_username = f'__vgh_migration_{user.pk}_{suffix}__'
            suffix += 1

        User.objects.using(database).filter(pk=user.pk).update(
            username=temporary_username
        )
        temporary_usernames.add(temporary_username)

    for user in users:
        base = re.sub(r'[^A-Za-z0-9_]+', '_', user.username).strip('_').lower()
        base = base or f'user{user.pk}'
        username = base[:150]
        suffix = 2

        while username.casefold() in used_usernames:
            suffix_text = f'_{suffix}'
            username = f'{base[:150 - len(suffix_text)]}{suffix_text}'
            suffix += 1

        used_usernames.add(username.casefold())
        User.objects.using(database).filter(pk=user.pk).update(username=username)

        display_name = ' '.join(
            part for part in (user.first_name, user.last_name) if part
        ).strip() or username
        profile, _ = UserProfile.objects.using(database).get_or_create(
            user_id=user.pk,
            defaults={'display_name': display_name},
        )
        if not profile.display_name:
            UserProfile.objects.using(database).filter(pk=profile.pk).update(
                display_name=display_name
            )


def add_case_insensitive_username_index(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor not in {'sqlite', 'postgresql'}:
        raise RuntimeError(
            'Case-insensitive username uniqueness migration supports SQLite and PostgreSQL.'
        )

    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    table = connection.ops.quote_name(User._meta.db_table)
    username_column = connection.ops.quote_name(User._meta.get_field('username').column)
    index_name = connection.ops.quote_name('auth_user_username_lower_uniq')
    schema_editor.execute(
        f'CREATE UNIQUE INDEX {index_name} ON {table} (LOWER({username_column}))'
    )


def remove_case_insensitive_username_index(apps, schema_editor):
    if schema_editor.connection.vendor not in {'sqlite', 'postgresql'}:
        return

    index_name = schema_editor.connection.ops.quote_name(
        'auth_user_username_lower_uniq'
    )
    schema_editor.execute(f'DROP INDEX IF EXISTS {index_name}')


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_community_deduplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RunPython(
            normalize_usernames_and_backfill_display_names,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            add_case_insensitive_username_index,
            remove_case_insensitive_username_index,
        ),
    ]
