# Generated by Django 6.0.2 on 2026-10-03 07:27

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    for model_name, prefix in (('Post', 'course'), ('Lesson', 'lesson')):
        model = apps.get_model('blog', model_name)
        used_slugs = set()
        for item in model.objects.order_by('pk').iterator():
            base = slugify(item.title) or f'{prefix}-{item.pk}'
            candidate = base
            suffix = 2
            while candidate in used_slugs:
                candidate = f'{base}-{suffix}'
                suffix += 1
            item.slug = candidate
            item.save(update_fields=['slug'])
            used_slugs.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_userblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
    ]
