# Generated by Django 6.0.2 on 2026-10-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_add_course_and_lesson_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('python', 'Learn Python'), ('full_stack', 'Become a Full Stack Developer'), ('django', 'Learn Django'), ('dsa', 'Improve DSA'), ('interview', 'Prepare for Interviews'), ('projects', 'Build Projects'), ('job', 'Get Job Ready'), ('other', 'Other'), ('skill', 'Learn a New Skill')], max_length=20, null=True),
        ),
    ]
