# Generated by Django 6.1.1 on 2026-10-08 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_alter_assignmentsubmission_file_aitutorconversation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('AI', 'AI'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('C++', 'C++'), ('C#', 'C#'), ('PHP', 'PHP'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust'), ('TypeScript', 'TypeScript'), ('SQL', 'SQL'), ('HTML/CSS', 'HTML/CSS'), ('Other', 'Other')], default='Other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_community_posts', to=settings.AUTH_USER_MODEL)),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_replies', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.communitypost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['category', '-created_at'], name='blog_commun_categor_b5f56c_idx'),
        ),
    ]
