# Generated by Django 6.1.1 on 2026-10-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_communitypost_communityreply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='community_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blog.communitypost'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW_REQUEST', 'Follow Request'), ('FOLLOW_ACCEPTED', 'Follow Accepted'), ('FOLLOW_REJECTED', 'Follow Rejected'), ('FOLLOW_BACK', 'Follow Back'), ('COMMUNITY_REPLY', 'Community Reply')], max_length=30),
        ),
    ]
