# Generated by Django 6.1.1 on 2026-10-08 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_notification_community_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_active_sessions',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to allow any number of concurrent sessions.', null=True, verbose_name='Maximum active sessions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_successful_logins',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for no lifetime successful-login limit.', null=True, verbose_name='Total successful-login allowance'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='successful_login_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Successful logins used'),
        ),
        migrations.CreateModel(
            name='PendingUserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True)),
                ('session_binding_digest', models.CharField(max_length=64)),
                ('login_method', models.CharField(default='Password', max_length=32)),
                ('backend_path', models.CharField(default='django.contrib.auth.backends.ModelBackend', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_login_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session_binding_digest', 'expires_at'], name='blog_pendin_session_291327_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('reservation_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('device_description', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_activity_at',),
                'indexes': [models.Index(fields=['user', 'is_active', 'expires_at'], name='blog_userlo_user_id_532e5c_idx')],
            },
        ),
    ]
