# Generated by Django 6.1.1 on 2026-10-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_userprofile_max_active_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leadership_badge_awarded',
            field=models.BooleanField(default=False, verbose_name='Leadership badge awarded'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leadership_badge_awarded_at',
            field=models.DateField(blank=True, null=True, verbose_name='Leadership badge award date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leadership_badge_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Leadership badge description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leadership_badge_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Leadership badge title'),
        ),
    ]
